# Generated by Django 5.0.6 on 2024-11-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='customer_id',
        ),
    ]
